language: node_js
node_js:
  - 'lts/*'
sudo: false
cache: npm
script:
  - npm run ci:lint
  - npm run ci:build
before_deploy: mv ci.gitignore .gitignore -f
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository
  keep-history: true
  on:
    branch: master
